   ###   Problem Statement 01
 Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

   HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def vandermonde(vector_list,N,increasing=False): 
    if increasing==True:
        return np.array([list(map(lambda x : x**i,vector_list)) for i in range(N)]).T
    if increasing==False:
          return np.array(list(reversed([list(map(lambda x : x**i,vector_list)) for i in range(N)]))).T

In [3]:
v=[2,3,4,1]

In [4]:
vandermonde(v,4)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])

In [5]:
vandermonde(v,4,True)

array([[ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64],
       [ 1,  1,  1,  1]])

### Built-in-function np.vander

In [6]:
np.vander(v,4,False)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])

In [7]:
np.vander(v,4,True)

array([[ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64],
       [ 1,  1,  1,  1]])

In [8]:
a=np.arange(1,11)

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.average(a[1:5])

3.5

   ###   Problem Statement 02
    Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
    the given sequence is defined as follows:
    The moving average sequence has n-k+1 elements as shown below.
    The moving averages with k=4 of a ten-value sequence (n=10) is shown below
    i 1 2 3 4 5 6 7 8 9 10
    ===== == == == == == == == == == ==
    Input 10 20 30 40 50 60 70 80 90 100
    y1 25 = (10+20+30+40)/4
    y2 35 = (20+30+40+50)/4
    y3 45 = (30+40+50+60)/4
    y4 55 = (40+50+60+70)/4
    y5 65 = (50+60+70+80)/4
    y6 75 = (60+70+80+90)/4
    y7 85 = (70+80+90+100)/4
    Thus, the moving average sequence has n-k+1=10-4+1=7 values.
  ###  Question: Write a function to find moving average in an array over a window:
    Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [11]:
def moving_average(array,window):

    for i in range(len(array)-window+1):
       
        print('y'+str(i+1)+' ---> '+str(round(np.average(a[i:i+window]),2)))
    

In [12]:
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [13]:
moving_average(a,3)

y1 ---> 5.0
y2 ---> 4.67
y3 ---> 5.67
y4 ---> 6.67
y5 ---> 9.67
y6 ---> 28.67
y7 ---> 49.33
y8 ---> 72.67
y9 ---> 84.0
y10 ---> 93.33
y11 ---> 116.33
